### ISSUE TITLE
Plus de DNS pour inetdoc.net

### ISSUE THREAD

**Issue by netro** [platu/inetdoc#5]
Bonjour,

Il ne semble plus avoir de résolution DNS pour inetdoc.net.

ns.inetdoc.net n'est pas joinable et NS1.7APOINTNU.FR ne fait pas (ou plus) de résolution de nom pour le domaine inetdoc.net

**Comment by platu** [comment]
Bonjour,
Tout est rentré dans l'ordre après un changement de machine d'hébergement.
C'est une leçon !
La résilience doit être améliorée :/
