### ISSUE TITLE
suggestion remplacement : crypter -> chiffrer

### ISSUE THREAD

**Issue by nragot** [platu/inetdoc#7]
Il me semble que les termes "crypter" et "encrypter" ne soient pas adaptés  :

1. [dans cette phrase](https://github.com/platu/inetdoc/blob/a6c5ee932d3b76389b8274de91abad8653fb90a8/guides/iptables-tutorial/chapters/introduction.xml#L104)
2. [et dans cet article à plusieurs endroit](https://github.com/platu/inetdoc/blob/a6c5ee932d3b76389b8274de91abad8653fb90a8/guides/tutoriel-secu/tutoriel.securite.xml)

Je suggère de les remplacer par "chiffrer". En effet, il me semble que "crypter" soit un non sens dans la mesure où il s'oppose à "décrypter" qui signifie un déchiffrage sans clefs (sommes toute, de briser la clefs). "Crypter" voudrait alors dire chiffrer sans clefs de chiffrement, ce qui serait absurde.

Toutefois, je ne suis pas un expert. Je me réfère à [ce site](https://chiffrer.info/) qui sera surement mieux défendre mon propos.

**Comment by platu** [comment]
Un grand merci pour cette suggestion tout à fait pertinente.

Voilà un moment que je n'avais pas ouvert les fichiers source de ces guides "historiques".

Les corrections étaient nombreuses : [commit](https://github.com/platu/inetdoc/commit/d14244093552b74136a8a488246896cd8e9236b0)

**Comment by nragot** [comment]
Le correctif ayant été fusioné avec la branche main, je ferme ce ticket.
Merci pour votre travail, ce guide est très utile !
